### ISSUE TITLE
defineComponent 

### ISSUE THREAD

**Issue by francoispothier** [scopewu/qrcode.vue#32]
I keep having this error
_Uncaught TypeError: vue.defineComponent is not a function_
coming from this file
_qrcode.vue.browser.js_

I am using the single file .vue component method

What am i missing?

**Comment by scopewu** [comment]
Hi @francoispothier 
  `vue.defineComponent` is a type method provided by Vue 3. `qrcode.vue` has been updated to provide support for Vue 3. If you are using Vue 2, please try using `qrcode.vue 1.x`.
  If the issue is not due to version, please provide the Vue and qrcode.vue versions, I can troubleshoot the issue.
  Have a great day.

**Comment by francoispothier** [comment]
Thank you for the quick response
It works just fine!
Have a nice day!
