### ISSUE TITLE
Breaking change in 3.5

### ISSUE THREAD

**Issue by adrium** [scopewu/qrcode.vue#85]
Hi, this following code used to work in 3.4: https://jsfiddle.net/d3ugkhaw/

Whereas it does not display any qr code in 3.5: https://jsfiddle.net/Ld42fm8z/

How should the snipped be adjusted to make it work in 3.5?

**Comment by scopewu** [comment]
Thanks a lot for the feedback, this issue is due to exporting the `QrcodeCanvas` and `QrcodeSvg` components independently in version 3.5 for easy standalone use.Yes, the rollup.js configuration has been changed:

```
// rollup.config.js

-    exports: 'default',
+    exports: 'named',
```

For the error you are reporting, you can use the `default` attribute, which I will refine in the documentation.

```js
Vue.createApp({
  data() { return {
    value: 'https://example.com',
    test: 'Hello World'
  }},
  components: {
    QrcodeVue: QrcodeVue.default,
  },
}).mount('#root')
```

非常感谢反馈问题，这个问题是由于在 3.5 版本中独立导出 `QrcodeCanvas` 和 `QrcodeSvg` 组件，方便独立使用。是的，修改了 rollup 配置。

针对您的报错，可以使用 `default` 属性，我会在文档中完善说明。

**Comment by adrium** [comment]
Sorry, I need to reopen and I discovered why my code is not working anymore (I actually did figure out using `QrcodeVue.QrcodeCanvas` when inspecting the object)

Adding `margin="0"` breaks:

3.4: https://jsfiddle.net/4y0htd9x/

3.5: https://jsfiddle.net/ets2z0o3/

**Comment by adrium** [comment]
Great, works now!
